### ISSUE TITLE
Is the build Possible in Windows?

### ISSUE THREAD

**Issue by SwordFish32** [MommaWatasu/Horse#1]
Is the build Possible in Windows?
Or can you just make a release with the .iso?

**Comment by MommaWatasu** [comment]
I think you can build it on Windows but I haven never tried. I’ll add the Action to build and deploy with the .iso(but not right now).

**Comment by MommaWatasu** [comment]
I created iso file as artifact of [Actions](https://github.com/MommaWatasu/Horse/actions/runs/8640367673). I don't know whether it works with VirtualBox or not, please but try it out.
Note: you have to enable UEFI booting of VirtualBox when you try.

**Comment by SwordFish32** [comment]
The .iso did not work for me. I tried the iso with VMware and virtual box (UEFI enabled), but it did not work in both. At the same time I could just emulate linux in them and run the commands listed in the README.md.
